spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      label: main
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
    rabbitmq:
      host: localhost
      password: guest
      port: 5672
      username: guest
  application:
    name: sgl-api-gateway

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
          - refresh

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
